### ISSUE TITLE
how can i change the MC_FIRST_USERNAME and MC_FIRST_PASSWORD?

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#38]
As you know,the MC_FIRST_USERNAME was in the mtwilson.env profile，but how can i change the MC_FIRST_USERNAME and MC_FIRST_PASSWORD?

**Comment by ryansavino** [comment]
For what purpose do you want to change it?

You can always create another user and make it an administrator.

**Comment by zhq0918** [comment]
because the MC_FIRST_USERNAME and MC_FIRST_PASSWORD are both in clear text.

**Comment by ryansavino** [comment]
The env file is there for installation purposes only. It is supposed to be removed after installation so that someone with system access cannot get credentials, etc. like you rightfully pointed out.

If you want to actually change the admin account, I would suggest creating a new user, making it an administrator, and deleting the old user. This can all be done from the portal.

**Comment by zhq0918** [comment]
ok,I see.thank you ransavion.
