### ISSUE TITLE
Compiler/installer should not install repositories on my system

### ISSUE THREAD

**Issue by jeefberkey** [opencit/opencit#69]
I see that `epel-testing` was installed on my machine during build. The installer should not do this automatically. 

When I tried to install my compiled `.bin`, that also adds a repo to my system. This is not ok.

**Comment by JordunoInt** [comment]
Hello Jeff,

What is the repo that you are trying to build?

Regards,
Jorge O.

**Comment by jeefberkey** [comment]
I have made a vagrant image that I use to make reproducible builds: https://github.com/jeefberkey/opencit-build

It follows the instructions in the wiki page as closely as it can.

**Comment by JordunoInt** [comment]
From what i can see in your files: deps.sh and ant.sh i couldn't find where you build (ant) the repo for the "external-artifacts" please let me know if im wrong.

Either way i can assure you that it is going to work with CentOS, if it does...please also let me know.

Please also let me know if this helps you or not, in order to keep digging on your issue.

Best Regards,
Jorge O.

**Comment by ryansavino** [comment]
Nick, there are options to not allow the addition of these repos to your system, but the installation will fail without the required packages.

**Comment by ddhawal** [comment]
@jeefberkey Please refer to the https://github.com/intel-secl/intel-secl for the latest version,
